### ISSUE TITLE
To-do, first things

### ISSUE THREAD

**Issue by elisaado** [hdevnotly/alpha#2]
## Todo list:

- [x] move from semantic to bootstrap
- [x] set up HTML5 BP with jQuery
- [x] make log in work with socket.io
- [x] check if logged in

**Comment by elisaado** [comment]
@hdev1 this is better :fox_face:

**Comment by hdev1** [comment]
Setting up login with socket.io.

**Comment by hdev1** [comment]
Fixed a lot of stuff.
Also, logging in now works. It returns an error or says Successfully logged in.
Next on the Todo list will be:
Storing the session info (username, password) locally. We won't be storing info on the server anymore, but we will encrypt the password. The key is randomly generated at every startup. At every connection, if the server gets the emit 'loggedin' (with a json array), it will take its info (school, user, pass), decrypt the password and log in. So every reload it logs in with Magister again.

**Comment by elisaado** [comment]
Alright! I can set up a domain with https too btw
